services:
  backend:
    build:
      context: ./AiExam
      dockerfile: Dockerfile
    container_name: aiexam-backend
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend,0.0.0.0
    stdin_open: true
    tty: true

  frontend:
    build:
      context: ./AiExam/frontend
      dockerfile: Dockerfile
    container_name: aiexam-frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./AiExam/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
