# Generated by Django 5.2.7 on 2025-11-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('family_name', models.CharField()),
                ('subject', models.CharField()),
            ],
        ),
    ]
