# Generated by Django 5.2.7 on 2025-11-07 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_student_user_teature_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='name',
            new_name='student_name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Student',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='exam',
            field=models.FileField(blank=True, null=True, upload_to='./uploads/json'),
        ),
        migrations.AddField(
            model_name='exam',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.student'),
        ),
        migrations.AddField(
            model_name='exam',
            name='upload_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
