# Generated by Django 5.2.7 on 2025-11-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_rename_name_exam_student_name_remove_exam_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='student_id',
            new_name='student',
        ),
    ]
