# Generated by Django 5.2.7 on 2025-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_rename_student_id_exam_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectExam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('upload_at', models.DateTimeField(auto_now=True)),
                ('exam_datetime', models.DateTimeField()),
                ('exam', models.FileField(blank=True, null=True, upload_to='./uploads/exams')),
            ],
        ),
    ]
