# Generated by Django 5.2.7 on 2025-12-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_exam_examparticipation'),
        ('exam', '0008_subjectexam'),
    ]

    operations = [
    ]
